using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;

namespace LocalIPv6 {
 public class RoutePlan {public string id,name,mark,service,note;public string[] hosts;}
 public class RoutingStatus {public bool active;public string sourceID;public string[] hosts;}
 public class RouteState {public List<RoutePlan> plans;public RoutingStatus routing;}
 public class RouteChoice {public string Label{get;set;}public string Host{get;set;}}
 public class SavedRoute {public string id,host;}
 public partial class DesktopApp {
  RouteState routeState;RoutePlan routePlan;bool routeBuilt;string currentPage="routing";string catalogFilter="";
  Dictionary<string,Button> routeCards=new Dictionary<string,Button>(); Dictionary<string,TextBlock> routeHealth=new Dictionary<string,TextBlock>(); List<FrameworkElement> categoryLabels=new List<FrameworkElement>(); Dictionary<string,Button> catalogCards=new Dictionary<string,Button>(); Dictionary<string,TextBlock> catalogHealth=new Dictionary<string,TextBlock>();
  string RoutePreferencePath{get{return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"EpicIPv6Helper","route-selection.json");}}
  UIElement PlatformIcon(string id,string mark,double size){
   try{using(var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("icons."+id)){if(stream!=null){var bitmap=BitmapFrame.Create(stream,BitmapCreateOptions.PreservePixelFormat,BitmapCacheOption.OnLoad);bitmap.Freeze();return new Image{Source=bitmap,Width=size,Height=size,Stretch=Stretch.Uniform};}}}catch{}
   return new TextBlock{Text=mark,FontWeight=FontWeights.Bold,FontSize=17,Foreground=Hex("#536FDB"),HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};
  }
  void BuildRouting(){
   BuildUpstreams(); N<TextBox>("PlatformSearch").TextChanged+=(s,e)=>{if(N<TextBox>("CatalogSearch").Text!=N<TextBox>("PlatformSearch").Text)N<TextBox>("CatalogSearch").Text=N<TextBox>("PlatformSearch").Text;FilterPlatforms();};N<TextBox>("CatalogSearch").TextChanged+=(s,e)=>{N<TextBox>("PlatformSearch").Text=N<TextBox>("CatalogSearch").Text;FilterPlatforms();};N<ComboBox>("CatalogCategory").SelectionChanged+=(s,e)=>FilterPlatforms();N<System.Windows.Controls.Primitives.UniformGrid>("RoutingCards").SizeChanged+=(s,e)=>{var grid=N<System.Windows.Controls.Primitives.UniformGrid>("RoutingCards");grid.Columns=grid.ActualWidth<820?3:4;};N<Button>("ChangePlatform").Click+=(s,e)=>ShowPicker(true);N<Button>("ViewSelected").Click+=(s,e)=>ShowPicker(false);
   N<Button>("RoutingNav").Click+=(s,e)=>{ShowPage("routing");ShowPicker(true);};
   N<Button>("StartRouting").Click+=async(s,e)=>await StartRouting();
   N<Button>("StopRouting").Click+=async(s,e)=>{await Restore();await PollRouting();};
   N<ComboBox>("RoutingChoice").SelectionChanged+=(s,e)=>{SaveRouteChoice();UpdateRoutingView();};
   N<Button>("RoutingDiagnostics").Click+=(s,e)=>{if(routePlan!=null&&routePlan.id=="epic"){ShowPage("epic");ShowOptimizer();return;}ShowPage("diagnostics");N<TextBox>("SourceSearch").Text=routePlan==null?"":routePlan.name.Replace(" 云文件","");};
   N<Button>("RoutingHelp").Click+=(s,e)=>ShowMessage("接管范围","启动后，已有 Clash 会把所选域名转给本助手，上游只连接 IPv6。\n\n浏览器和使用系统代理的客户端可按原方式下载，不用把文件地址填到助手。已建立的目标连接会重连。\n\n不读取系统代理的客户端，需要先设置为你原有的 Clash 代理地址；此项不是全系统强制拦截。QUIC / UDP、未知重定向域名和绕过代理的请求不在保证范围内。\n\n此版同时启用一组服务，切换时恢复上一组再应用新规则。记住你的平台与服务选择，但重启不会自动修改网络。停止或退出会恢复原配置。");
  }
  async Task PollRouting(){
   routeState=json.Deserialize<RouteState>(await http.GetStringAsync("http://127.0.0.1:17890/api/routing"));
   if(!routeBuilt){routeBuilt=true;foreach(var group in routeState.plans.GroupBy(p=>PlatformCategory(p)).OrderBy(g=>g.Key=="游戏与引擎"?"":g.Key)){var heading=Text(group.Key,11,true);heading.Margin=new Thickness(10,14,0,6);heading.SetResourceReference(TextBlock.ForegroundProperty,"Muted");heading.Tag=group.Select(p=>p.id).ToArray();categoryLabels.Add(heading);N<StackPanel>("PlatformList").Children.Add(heading);foreach(var plan in group){var p=plan;var content=new Grid();content.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(36)});content.ColumnDefinitions.Add(new ColumnDefinition());content.Children.Add(new Border{Background=Hex(p.id=="pypi"||p.id=="zenodo"?"#496CAD":"#FFFFFF"),CornerRadius=new CornerRadius(8),Width=32,Height=32,Padding=new Thickness(4),Child=PlatformIcon(p.id,p.mark,24)});var labels=new StackPanel{Margin=new Thickness(9,0,0,0),VerticalAlignment=VerticalAlignment.Center};var name=Text(p.name,12,true);name.Margin=new Thickness(0);name.TextWrapping=TextWrapping.NoWrap;name.TextTrimming=TextTrimming.CharacterEllipsis;labels.Children.Add(name);var health=Text("未检测",10);health.Margin=new Thickness(0,3,0,0);health.SetResourceReference(TextBlock.ForegroundProperty,"Muted");routeHealth[p.id]=health;labels.Children.Add(health);Grid.SetColumn(labels,1);content.Children.Add(labels);var button=new Button{Content=content,HorizontalContentAlignment=HorizontalAlignment.Stretch,Height=61,Margin=new Thickness(1,2,4,3),Padding=new Thickness(9,6,8,6),ToolTip=p.name+" · "+p.service};button.Click+=(s,e)=>SelectRoute(p,"");routeCards[p.id]=button;N<StackPanel>("PlatformList").Children.Add(button);}}
    N<ComboBox>("CatalogCategory").ItemsSource=new[]{"全部分类"}.Concat(routeState.plans.Select(p=>PlatformCategory(p)).Distinct()).ToArray();N<ComboBox>("CatalogCategory").SelectedIndex=0;foreach(var plan in routeState.plans){var p=plan;var card=new Grid();card.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(48)});card.ColumnDefinitions.Add(new ColumnDefinition());card.Children.Add(new Border{Width=44,Height=44,CornerRadius=new CornerRadius(11),Background=Hex(p.id=="pypi"||p.id=="zenodo"?"#496CAD":"#FFFFFF"),Padding=new Thickness(4),VerticalAlignment=VerticalAlignment.Top,Child=PlatformIcon(p.id,p.mark,36)});var labels=new StackPanel{Margin=new Thickness(9,0,0,0)};var name=Text(p.name,13,true);name.Margin=new Thickness(0,0,0,4);name.MaxHeight=40;labels.Children.Add(name);var service=Text(p.service.Replace(" · 已登记下载域名",""),10);service.Margin=new Thickness(0,0,0,4);service.MaxHeight=32;service.SetResourceReference(TextBlock.ForegroundProperty,"Muted");labels.Children.Add(service);var health=Text("未检测",10);health.Margin=new Thickness(0);health.SetResourceReference(TextBlock.ForegroundProperty,"Accent");catalogHealth[p.id]=health;labels.Children.Add(health);Grid.SetColumn(labels,1);card.Children.Add(labels);var button=new Button{Content=card,Height=118,HorizontalContentAlignment=HorizontalAlignment.Stretch,Padding=new Thickness(12,14,10,10),Margin=new Thickness(0,0,10,10),ToolTip=p.name+" · "+p.note};button.Click+=(s,e)=>SelectRoute(p,"");catalogCards[p.id]=button;N<System.Windows.Controls.Primitives.UniformGrid>("RoutingCards").Children.Add(button);}SavedRoute saved=null;try{saved=json.Deserialize<SavedRoute>(File.ReadAllText(RoutePreferencePath));}catch{}var initial=routeState.plans.FirstOrDefault(p=>saved!=null&&p.id==saved.id)??routeState.plans.First();SelectRoute(initial,saved==null?"":saved.host);ShowPicker(true);
   }
   UpdatePlatformHealth();UpdateRoutingView();await PollUpstreams();
  }
  string PlatformCategory(RoutePlan p){var s=(researchState.sources??new List<ResearchSource>()).FirstOrDefault(x=>x.id==p.id);return p.id=="epic"?"游戏与引擎":s==null?"科研来源":s.category;}
  void ShowPicker(bool show){N<Border>("CatalogPanel").Visibility=show?Visibility.Visible:Visibility.Collapsed;N<StackPanel>("RoutingDetails").Visibility=show?Visibility.Collapsed:Visibility.Visible;N<Button>("ChangePlatform").Visibility=show?Visibility.Collapsed:Visibility.Visible;N<TextBlock>("CatalogSelection").Text=routePlan==null?"请选择平台":"当前选择："+routePlan.name;N<ScrollViewer>("RoutingScroll").ScrollToTop();}
  void UpdatePlatformHealth(){foreach(var pair in routeHealth){var h=(researchState.health??new List<SourceHealth>()).FirstOrDefault(x=>x.id==pair.Key);pair.Value.Text=pair.Key=="epic"?"UE / 游戏 CDN":h==null?"未检测":h.status;TextBlock label;if(catalogHealth.TryGetValue(pair.Key,out label))label.Text=pair.Value.Text;}FilterPlatforms();}
  void FilterPlatforms(){if(routeState==null)return;string query=N<TextBox>("PlatformSearch").Text.Trim();string category=N<ComboBox>("CatalogCategory").SelectedItem as string;string nextFilter=query+"|"+category;if(nextFilter!=catalogFilter){catalogFilter=nextFilter;window.Dispatcher.BeginInvoke(System.Windows.Threading.DispatcherPriority.Loaded,new Action(()=>N<ScrollViewer>("CatalogScroll").ScrollToTop()));}int visible=0;foreach(var p in routeState.plans){Button b;if(!routeCards.TryGetValue(p.id,out b))continue;bool match=query.Length==0||(p.name+PlatformCategory(p)+String.Join(" ",p.hosts)+routeHealth[p.id].Text).IndexOf(query,StringComparison.OrdinalIgnoreCase)>=0;b.Visibility=match?Visibility.Visible:Visibility.Collapsed;Button card;if(catalogCards.TryGetValue(p.id,out card))card.Visibility=match&&(String.IsNullOrEmpty(category)||category=="全部分类"||category==PlatformCategory(p))?Visibility.Visible:Visibility.Collapsed;if(card!=null&&card.Visibility==Visibility.Visible)visible++;}foreach(var label in categoryLabels)label.Visibility=((string[])label.Tag).Any(id=>routeCards[id].Visibility==Visibility.Visible)?Visibility.Visible:Visibility.Collapsed;N<TextBlock>("PlatformCount").Text=routeCards.Count+" 个来源 · 可搜索";N<TextBlock>("CatalogCount").Text=visible+" / "+routeCards.Count+" 个来源";}
  void SelectRoute(RoutePlan plan,string host){routePlan=plan;ShowPage("routing");ShowPicker(false);N<Border>("RoutingHeroIcon").Background=Hex(plan.id=="pypi"||plan.id=="zenodo"?"#496CAD":"#FFFFFF");N<Border>("RoutingHeroIcon").Child=PlatformIcon(plan.id,plan.mark,42);N<TextBlock>("RoutingTitle").Text=plan.name;N<TextBlock>("RoutingService").Text=plan.service;N<TextBlock>("RoutingScope").Text=plan.note;var choices=new List<RouteChoice>{new RouteChoice{Label=plan.service+"（全部已接入域名）",Host=""}};if(plan.hosts.Length>1)choices.AddRange(plan.hosts.Select(h=>new RouteChoice{Label="仅 "+h,Host=h}));N<ComboBox>("RoutingChoice").ItemsSource=choices;N<ComboBox>("RoutingChoice").SelectedItem=choices.FirstOrDefault(c=>c.Host==host)??choices.First();UpdateRoutingView();}
  void SaveRouteChoice(){var choice=N<ComboBox>("RoutingChoice").SelectedItem as RouteChoice;if(routePlan==null||choice==null)return;try{Directory.CreateDirectory(Path.GetDirectoryName(RoutePreferencePath));File.WriteAllText(RoutePreferencePath,json.Serialize(new SavedRoute{id=routePlan.id,host=choice.Host}),Encoding.UTF8);}catch(Exception e){Log("选择未能保存："+e.Message);}}
  void UpdateRoutingView(){if(routePlan==null||routeState==null)return;var choice=N<ComboBox>("RoutingChoice").SelectedItem as RouteChoice;var selectedHosts=choice!=null&&!String.IsNullOrEmpty(choice.Host)?new[]{choice.Host}:routePlan.hosts;SetNodeHosts(selectedHosts);N<TextBlock>("RoutingDomains").Text="接管域名："+String.Join("  ·  ",selectedHosts);var active=routeState.routing!=null&&routeState.routing.active;var same=active&&routeState.routing.sourceID==routePlan.id&&routeState.routing.hosts.OrderBy(h=>h).SequenceEqual(selectedHosts.OrderBy(h=>h));var name=active?routeState.plans.FirstOrDefault(p=>p.id==routeState.routing.sourceID):null;N<TextBlock>("RoutingActive").Text=active?"当前接管："+(name==null?routeState.routing.sourceID:name.name)+" · "+routeState.routing.hosts.Length+" 个域名":"尚未接管 · 选好平台后点击启动";N<Button>("StartRouting").Content=busy?"正在应用…":same?"✓ 已启用所选服务":active?"切换到此服务":"▷ 启动 IPv6 接管";N<Button>("StartRouting").IsEnabled=ready&&!busy&&!same;N<Button>("StopRouting").IsEnabled=ready&&!busy&&active;N<ComboBox>("RoutingChoice").IsEnabled=!busy;
   foreach(var c in routeCards){c.Value.SetResourceReference(Button.BackgroundProperty,c.Key==routePlan.id&&currentPage=="routing"?"Soft":"Panel");c.Value.SetResourceReference(Button.BorderBrushProperty,c.Key==routePlan.id&&currentPage=="routing"?"Accent":"Line");c.Value.IsEnabled=!busy;}foreach(var c in catalogCards){c.Value.SetResourceReference(Button.BackgroundProperty,c.Key==routePlan.id?"Soft":"Panel");c.Value.SetResourceReference(Button.BorderBrushProperty,c.Key==routePlan.id?"Accent":"Line");c.Value.IsEnabled=!busy;} UpdateNodeControls();
  }
  async Task ApplyRoute(string id,string host){var request=new HttpRequestMessage(HttpMethod.Post,"http://127.0.0.1:17890/api/routing/start");request.Headers.Add("X-Token",token);request.Content=new StringContent(json.Serialize(new{id=id,host=host}),Encoding.UTF8,"application/json");using(var response=await http.SendAsync(request)){var text=await response.Content.ReadAsStringAsync();if(!response.IsSuccessStatusCode)throw new Exception(text.Trim());}}
  async Task StartRouting(){if(busy||routePlan==null)return;var choice=N<ComboBox>("RoutingChoice").SelectedItem as RouteChoice;busy=true;UpdateRoutingView();UpdateControls();Log("正在应用 "+routePlan.name+" 的下载规则…");try{await ApplyRoute(routePlan.id,choice==null?"":choice.Host);Log("已启用 "+routePlan.name+"：在原网站 / 客户端照常下载即可。");}catch(Exception e){ShowMessage("接管未完成",e.Message+"\n请保持已有 Clash 运行并处于规则模式；没有回退 IPv4。");}finally{busy=false;}await Poll();}
 }
}



