using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Reflection;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Media;
using System.Windows.Media.Imaging;

namespace LocalIPv6 {
 public class RoutePlan {public string id,name,mark,service,note;public string[] hosts;}
 public class RoutingStatus {public bool active;public string sourceID,mode;public string[] hosts;}
 public class SteamStatus {public bool clientFound,active;public string detail;public string[] hosts,detectedHosts;}
 public class RouteState {public List<RoutePlan> plans;public RoutingStatus routing;}
 public class RouteChoice {public string Label{get;set;}public string Host{get;set;}}
 public class SavedRoute {public string id,host;}
 public partial class DesktopApp {
  RouteState routeState;RoutePlan routePlan;SteamStatus steamState;bool routeBuilt;string currentPage="routing";string catalogFilter="";
  Dictionary<string,Button> routeCards=new Dictionary<string,Button>(); Dictionary<string,TextBlock> routeHealth=new Dictionary<string,TextBlock>(); List<FrameworkElement> categoryLabels=new List<FrameworkElement>(); Dictionary<string,Button> catalogCards=new Dictionary<string,Button>(); Dictionary<string,TextBlock> catalogHealth=new Dictionary<string,TextBlock>();
  string RoutePreferencePath{get{return Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData),"EpicIPv6Helper","route-selection.json");}}
  UIElement PlatformIcon(string id,string mark,double size){
   try{using(var stream=Assembly.GetExecutingAssembly().GetManifestResourceStream("icons."+id)){if(stream!=null){var bitmap=BitmapFrame.Create(stream,BitmapCreateOptions.PreservePixelFormat,BitmapCacheOption.OnLoad);bitmap.Freeze();return new Image{Source=bitmap,Width=size,Height=size,Stretch=Stretch.Uniform};}}}catch{}
   return new TextBlock{Text=mark,FontWeight=FontWeights.Bold,FontSize=17,Foreground=Hex("#536FDB"),HorizontalAlignment=HorizontalAlignment.Center,VerticalAlignment=VerticalAlignment.Center};
  }
  void BuildRouting(){
   BuildUpstreams(); N<TextBox>("PlatformSearch").TextChanged+=(s,e)=>{if(N<TextBox>("CatalogSearch").Text!=N<TextBox>("PlatformSearch").Text)N<TextBox>("CatalogSearch").Text=N<TextBox>("PlatformSearch").Text;FilterPlatforms();};N<TextBox>("CatalogSearch").TextChanged+=(s,e)=>{N<TextBox>("PlatformSearch").Text=N<TextBox>("CatalogSearch").Text;FilterPlatforms();};N<ComboBox>("CatalogCategory").SelectionChanged+=(s,e)=>FilterPlatforms();N<System.Windows.Controls.Primitives.UniformGrid>("RoutingCards").SizeChanged+=(s,e)=>{var grid=N<System.Windows.Controls.Primitives.UniformGrid>("RoutingCards");grid.Columns=grid.ActualWidth<820?3:4;};N<Button>("ChangePlatform").Click+=(s,e)=>ShowPicker(true);N<Button>("ViewSelected").Click+=(s,e)=>ShowPicker(false);
   N<Button>("RoutingNav").Click+=(s,e)=>{ShowPage("routing");ShowPicker(true);};
   N<Button>("StartRouting").Click+=async(s,e)=>await StartRouting();
   N<Button>("StopRouting").Click+=async(s,e)=>{await Restore();await PollRouting();};
   N<ComboBox>("RoutingChoice").SelectionChanged+=(s,e)=>{SaveRouteChoice();UpdateRoutingView();};
   N<Button>("RoutingDiagnostics").Click+=async(s,e)=>{if(routePlan!=null&&routePlan.id=="steam"){await VerifySteam();return;}if(routePlan!=null&&routePlan.id=="epic"){ShowPage("epic");ShowOptimizer();return;}ShowPage("diagnostics");N<TextBox>("SourceSearch").Text=routePlan==null?"":routePlan.name.Replace(" 云文件","");};
   N<Button>("RefreshSteamServers").Click+=async(s,e)=>await RefreshSteamServers();
   N<Button>("RoutingHelp").Click+=(s,e)=>{if(routePlan!=null&&routePlan.id=="steam"){ShowMessage("Steam 下载接管范围","助手从本机 Steam 下载日志读取精确服务器域名，启动后将所选域名映射到本机双栈回环，再由助手连接官方 CDN IPv6。Steam 游戏下载不依赖 Clash；HTTPS 保留原请求域名与证书验证，不解密流量。\n\n请先在 Steam 开始一次游戏下载，再点击“刷新下载服务器”。启用或更新服务器后，在 Steam 中暂停 → 继续，让旧连接重新建立。新增下载域名需要再次刷新并重新应用。\n\n修改 hosts 需要管理员权限。若启用失败，请先恢复并退出助手，右键本软件选择“以管理员身份运行”。\n\n本功能仅覆盖所选下载域名，不代表 Steam 登录、商店、联机或全机流量均走 IPv6。无 IPv6 或被服务器拒绝时会停止转发；可停止并恢复后使用原下载方式。");return;}ShowMessage("接管范围","启动后，已有 Clash 会把所选域名转给本助手，上游只连接 IPv6。\n\n浏览器和使用系统代理的客户端可按原方式下载，不用把文件地址填到助手。已建立的目标连接会重连。\n\n不读取系统代理的客户端，需要先设置为你原有的 Clash 代理地址；此项不是全系统强制拦截。QUIC / UDP、未知重定向域名和绕过代理的请求不在保证范围内。\n\n此版同时启用一组服务，切换时恢复上一组再应用新规则。记住你的平台与服务选择，但重启不会自动修改网络。停止或退出会恢复原配置。");};
  }
  async Task PollRouting(){
   routeState=json.Deserialize<RouteState>(await http.GetStringAsync("http://127.0.0.1:17890/api/routing"));
   routeState.plans=routeState.plans??new List<RoutePlan>();foreach(var plan in routeState.plans)plan.hosts=plan.hosts??new string[0];
   if(routeState.routing!=null)routeState.routing.hosts=routeState.routing.hosts??new string[0];
   if(!routeBuilt){routeBuilt=true;foreach(var group in routeState.plans.GroupBy(p=>PlatformCategory(p)).OrderBy(g=>g.Key=="游戏与引擎"?"":g.Key)){var heading=Text(group.Key,11,true);heading.Margin=new Thickness(10,14,0,6);heading.SetResourceReference(TextBlock.ForegroundProperty,"Muted");heading.Tag=group.Select(p=>p.id).ToArray();categoryLabels.Add(heading);N<StackPanel>("PlatformList").Children.Add(heading);foreach(var plan in group){var p=plan;var content=new Grid();content.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(36)});content.ColumnDefinitions.Add(new ColumnDefinition());content.Children.Add(new Border{Background=Hex(p.id=="pypi"||p.id=="zenodo"?"#496CAD":"#FFFFFF"),CornerRadius=new CornerRadius(8),Width=32,Height=32,Padding=new Thickness(4),Child=PlatformIcon(p.id,p.mark,24)});var labels=new StackPanel{Margin=new Thickness(9,0,0,0),VerticalAlignment=VerticalAlignment.Center};var name=Text(p.name,12,true);name.Margin=new Thickness(0);name.TextWrapping=TextWrapping.NoWrap;name.TextTrimming=TextTrimming.CharacterEllipsis;labels.Children.Add(name);var health=Text("未检测",10);health.Margin=new Thickness(0,3,0,0);health.SetResourceReference(TextBlock.ForegroundProperty,"Muted");routeHealth[p.id]=health;labels.Children.Add(health);Grid.SetColumn(labels,1);content.Children.Add(labels);var button=new Button{Content=content,HorizontalContentAlignment=HorizontalAlignment.Stretch,Height=61,Margin=new Thickness(1,2,4,3),Padding=new Thickness(9,6,8,6),ToolTip=p.name+" · "+p.service};button.Click+=(s,e)=>SelectRoute(p,"");routeCards[p.id]=button;N<StackPanel>("PlatformList").Children.Add(button);}}
    N<ComboBox>("CatalogCategory").ItemsSource=new[]{"全部分类"}.Concat(routeState.plans.Select(p=>PlatformCategory(p)).Distinct()).ToArray();N<ComboBox>("CatalogCategory").SelectedIndex=0;foreach(var plan in routeState.plans){var p=plan;var card=new Grid();card.ColumnDefinitions.Add(new ColumnDefinition{Width=new GridLength(48)});card.ColumnDefinitions.Add(new ColumnDefinition());card.Children.Add(new Border{Width=44,Height=44,CornerRadius=new CornerRadius(11),Background=Hex(p.id=="pypi"||p.id=="zenodo"?"#496CAD":"#FFFFFF"),Padding=new Thickness(4),VerticalAlignment=VerticalAlignment.Top,Child=PlatformIcon(p.id,p.mark,36)});var labels=new StackPanel{Margin=new Thickness(9,0,0,0)};var name=Text(p.name,13,true);name.Margin=new Thickness(0,0,0,4);name.MaxHeight=40;labels.Children.Add(name);var service=Text(p.service.Replace(" · 已登记下载域名",""),10);service.Margin=new Thickness(0,0,0,4);service.MaxHeight=32;service.SetResourceReference(TextBlock.ForegroundProperty,"Muted");labels.Children.Add(service);var health=Text("未检测",10);health.Margin=new Thickness(0);health.SetResourceReference(TextBlock.ForegroundProperty,"Accent");catalogHealth[p.id]=health;labels.Children.Add(health);Grid.SetColumn(labels,1);card.Children.Add(labels);var button=new Button{Content=card,Height=118,HorizontalContentAlignment=HorizontalAlignment.Stretch,Padding=new Thickness(12,14,10,10),Margin=new Thickness(0,0,10,10),ToolTip=p.name+" · "+p.note};button.Click+=(s,e)=>SelectRoute(p,"");catalogCards[p.id]=button;N<System.Windows.Controls.Primitives.UniformGrid>("RoutingCards").Children.Add(button);}SavedRoute saved=null;try{saved=json.Deserialize<SavedRoute>(File.ReadAllText(RoutePreferencePath));}catch{}var initial=routeState.plans.FirstOrDefault(p=>saved!=null&&p.id==saved.id)??routeState.plans.First();SelectRoute(initial,saved==null?"":saved.host);ShowPicker(true);
   }
   if(routePlan!=null){var latest=routeState.plans.FirstOrDefault(p=>p.id==routePlan.id);if(latest!=null){bool hostsChanged=!(routePlan.hosts??new string[0]).SequenceEqual(latest.hosts);routePlan=latest;if(hostsChanged)UpdateRouteChoices(CurrentRouteHost);}}
   if(routePlan!=null&&routePlan.id=="steam"){try{steamState=json.Deserialize<SteamStatus>(await http.GetStringAsync("http://127.0.0.1:17890/api/steam"));}catch(Exception e){N<TextBlock>("SteamDiscovery").Text="读取 Steam 服务器状态失败："+e.Message;}}
   UpdatePlatformHealth();UpdateRoutingView();await PollUpstreams();
  }
  string PlatformCategory(RoutePlan p){var s=(researchState.sources??new List<ResearchSource>()).FirstOrDefault(x=>x.id==p.id);return p.id=="epic"||p.id=="steam"?"游戏与引擎":s==null?"科研来源":s.category;}
  void ShowPicker(bool show){N<Border>("CatalogPanel").Visibility=show?Visibility.Visible:Visibility.Collapsed;N<StackPanel>("RoutingDetails").Visibility=show?Visibility.Collapsed:Visibility.Visible;N<Button>("ChangePlatform").Visibility=show?Visibility.Collapsed:Visibility.Visible;N<TextBlock>("CatalogSelection").Text=routePlan==null?"请选择平台":"当前选择："+routePlan.name;N<ScrollViewer>("RoutingScroll").ScrollToTop();}
  void UpdatePlatformHealth(){foreach(var pair in routeHealth){var h=(researchState.health??new List<SourceHealth>()).FirstOrDefault(x=>x.id==pair.Key);pair.Value.Text=pair.Key=="steam"?(state.steamActive?"已启用 · 需实际验收":"需实际验收"):pair.Key=="epic"?"UE / 游戏 CDN":h==null?"未检测":h.status;TextBlock label;if(catalogHealth.TryGetValue(pair.Key,out label))label.Text=pair.Value.Text;}FilterPlatforms();}
  void FilterPlatforms(){if(routeState==null)return;string query=N<TextBox>("PlatformSearch").Text.Trim();string category=N<ComboBox>("CatalogCategory").SelectedItem as string;string nextFilter=query+"|"+category;if(nextFilter!=catalogFilter){catalogFilter=nextFilter;window.Dispatcher.BeginInvoke(System.Windows.Threading.DispatcherPriority.Loaded,new Action(()=>N<ScrollViewer>("CatalogScroll").ScrollToTop()));}int visible=0;foreach(var p in routeState.plans){Button b;if(!routeCards.TryGetValue(p.id,out b))continue;bool match=query.Length==0||(p.name+PlatformCategory(p)+String.Join(" ",p.hosts)+routeHealth[p.id].Text).IndexOf(query,StringComparison.OrdinalIgnoreCase)>=0;b.Visibility=match?Visibility.Visible:Visibility.Collapsed;Button card;if(catalogCards.TryGetValue(p.id,out card))card.Visibility=match&&(String.IsNullOrEmpty(category)||category=="全部分类"||category==PlatformCategory(p))?Visibility.Visible:Visibility.Collapsed;if(card!=null&&card.Visibility==Visibility.Visible)visible++;}foreach(var label in categoryLabels)label.Visibility=((string[])label.Tag).Any(id=>routeCards[id].Visibility==Visibility.Visible)?Visibility.Visible:Visibility.Collapsed;N<TextBlock>("PlatformCount").Text=routeCards.Count+" 个来源 · 可搜索";N<TextBlock>("CatalogCount").Text=visible+" / "+routeCards.Count+" 个来源";}
  string CurrentRouteHost{get{var choice=N<ComboBox>("RoutingChoice").SelectedItem as RouteChoice;return choice==null?"":choice.Host;}}
  void UpdateRouteChoices(string host){if(routePlan==null)return;var hosts=routePlan.hosts??new string[0];var choices=new List<RouteChoice>{new RouteChoice{Label=routePlan.service+(hosts.Length==0?"（尚未发现下载服务器）":"（全部已接入域名）"),Host=""}};if(hosts.Length>1)choices.AddRange(hosts.Select(h=>new RouteChoice{Label="仅 "+h,Host=h}));N<ComboBox>("RoutingChoice").ItemsSource=choices;N<ComboBox>("RoutingChoice").SelectedItem=choices.FirstOrDefault(c=>c.Host==host)??choices.First();}
  void SelectRoute(RoutePlan plan,string host){routePlan=routeState==null?plan:routeState.plans.FirstOrDefault(p=>p.id==plan.id)??plan;ShowPage("routing");ShowPicker(false);N<Border>("RoutingHeroIcon").Background=Hex(routePlan.id=="pypi"||routePlan.id=="zenodo"?"#496CAD":"#FFFFFF");N<Border>("RoutingHeroIcon").Child=PlatformIcon(routePlan.id,routePlan.mark,42);N<TextBlock>("RoutingTitle").Text=routePlan.name;N<TextBlock>("RoutingService").Text=routePlan.service;N<TextBlock>("RoutingScope").Text=routePlan.note;UpdateRouteChoices(host);UpdateRoutingView();}
  void SaveRouteChoice(){var choice=N<ComboBox>("RoutingChoice").SelectedItem as RouteChoice;if(routePlan==null||choice==null)return;try{Directory.CreateDirectory(Path.GetDirectoryName(RoutePreferencePath));File.WriteAllText(RoutePreferencePath,json.Serialize(new SavedRoute{id=routePlan.id,host=choice.Host}),Encoding.UTF8);}catch(Exception e){Log("选择未能保存："+e.Message);}}
  void UpdateRoutingView(){if(routePlan==null||routeState==null)return;bool steam=routePlan.id=="steam";var choice=N<ComboBox>("RoutingChoice").SelectedItem as RouteChoice;var selectedHosts=choice!=null&&!String.IsNullOrEmpty(choice.Host)?new[]{choice.Host}:routePlan.hosts??new string[0];SetNodeHosts(selectedHosts);N<TextBlock>("RoutingDomains").Text=selectedHosts.Length>0?"接管域名："+String.Join("  ·  ",selectedHosts):"尚未发现下载域名，请先在 Steam 开始下载，再刷新下载服务器。";var active=routeState.routing!=null&&routeState.routing.active;var same=active&&routeState.routing.sourceID==routePlan.id&&routeState.routing.hosts.OrderBy(h=>h).SequenceEqual(selectedHosts.OrderBy(h=>h));var name=active?routeState.plans.FirstOrDefault(p=>p.id==routeState.routing.sourceID):null;N<TextBlock>("RoutingActive").Text=active?"当前接管："+(name==null?routeState.routing.sourceID:name.name)+" · "+routeState.routing.hosts.Length+" 个域名"+(routeState.routing.sourceID=="steam"?" · 本机 hosts":" · Clash 规则"):"尚未接管 · 选好平台后点击启动";N<Button>("StartRouting").Content=busy?"正在处理…":same?"✓ 已启用所选服务":active?"切换到此服务":"▷ 启动 IPv6 接管";N<Button>("StartRouting").IsEnabled=ready&&!busy&&!same&&selectedHosts.Length>0;N<Button>("StopRouting").IsEnabled=ready&&!busy&&active;N<ComboBox>("RoutingChoice").IsEnabled=!busy;
   N<StackPanel>("SteamControls").Visibility=steam?Visibility.Visible:Visibility.Collapsed;N<Button>("RefreshSteamServers").IsEnabled=ready&&!busy;N<Button>("RoutingDiagnostics").Content=steam?"验证 Steam 下载链路":"查看来源检测";N<Button>("RoutingDiagnostics").IsEnabled=ready&&!busy;N<TextBlock>("RoutingMethod").Text=steam?"Steam：精确下载域名 → 本机 hosts 双栈回环 → 官方 CDN IPv6。管理员权限用于修改 hosts，启用后请在 Steam 暂停 → 继续。":"通过本机已有 Clash 接管所选域名。客户端需要使用系统代理或已有 Clash 代理；未经过代理的流量不受控制。";
   if(steam){N<TextBlock>("SteamDiscovery").Text=steamState==null?"正在读取 Steam 下载服务器…":(steamState.clientFound?"已找到本机 Steam":"未找到本机 Steam 客户端")+" · "+(steamState.detectedHosts??new string[0]).Length+" 个日志下载域名\n"+(steamState.detail??"")+"\n启用并检测实际下载块后，再判断本次连接是否通过。";}
   foreach(var c in routeCards){c.Value.SetResourceReference(Button.BackgroundProperty,c.Key==routePlan.id&&currentPage=="routing"?"Soft":"Panel");c.Value.SetResourceReference(Button.BorderBrushProperty,c.Key==routePlan.id&&currentPage=="routing"?"Accent":"Line");c.Value.IsEnabled=!busy;}foreach(var c in catalogCards){c.Value.SetResourceReference(Button.BackgroundProperty,c.Key==routePlan.id?"Soft":"Panel");c.Value.SetResourceReference(Button.BorderBrushProperty,c.Key==routePlan.id?"Accent":"Line");c.Value.IsEnabled=!busy;} UpdateNodeControls();
  }
  async Task ApplyRoute(string id,string host){var request=new HttpRequestMessage(HttpMethod.Post,"http://127.0.0.1:17890/api/routing/start");request.Headers.Add("X-Token",token);request.Content=new StringContent(json.Serialize(new{id=id,host=host}),Encoding.UTF8,"application/json");using(var response=await http.SendAsync(request)){var text=await response.Content.ReadAsStringAsync();if(!response.IsSuccessStatusCode)throw new Exception(text.Trim());}}
  async Task StartRouting(){if(busy||routePlan==null)return;bool steam=routePlan.id=="steam";var choice=N<ComboBox>("RoutingChoice").SelectedItem as RouteChoice;busy=true;UpdateRoutingView();UpdateControls();Log("正在应用 "+routePlan.name+" 的下载规则…");try{await ApplyRoute(routePlan.id,choice==null?"":choice.Host);Log(steam?"已启用 Steam 下载域名接管，请在 Steam 暂停 → 继续，再运行实际下载块验收。":"已启用 "+routePlan.name+"：在原网站 / 客户端照常下载即可。");}catch(Exception e){ShowMessage("接管未完成",e.Message+(steam?"\n若提示 hosts 被占用，请先暂停 Steam 下载后稍候重试；需要提权时再以管理员身份运行。没有回退 IPv4。":"\n请保持已有 Clash 运行并处于规则模式；没有回退 IPv4。"));}finally{busy=false;UpdateRoutingView();UpdateControls();}await Poll();}
  async Task RefreshSteamServers(){if(busy||!ready||routePlan==null||routePlan.id!="steam")return;busy=true;UpdateRoutingView();UpdateControls();Log("正在读取 Steam 下载日志中的服务器…");try{steamState=json.Deserialize<SteamStatus>(await Post("steam/refresh"));await PollRouting();Log("已刷新 Steam 下载服务器。启用中的域名若有变化，请重新应用，并在 Steam 暂停 → 继续。");}catch(Exception e){ShowMessage("服务器刷新未完成",e.Message+"\n请先在 Steam 开始一次游戏下载，确保下载日志可读取。");}finally{busy=false;UpdateRoutingView();UpdateControls();}await Poll();}
  async Task VerifySteam(){if(busy||!ready)return;busy=true;UpdateRoutingView();UpdateControls();var root=Dialog("Steam IPv6 链路验收","下载真实 Steam 数据块，校验 TLS 和内容，并检查助手的 IPv6 转发。通常需要 15–90 秒。通过只证明本次助手链路；Steam 客户端接管还需启用 hosts 后检查实际进程连接。");var progress=Text("正在检测 Steam 实际下载块…",16,true);root.Children.Add(progress);Log("正在进行 Steam 下载块与 IPv6 出站验收。");try{var report=json.Deserialize<Verification>(await Post("steam/verify"));root.Children.Clear();root.Children.Add(Text(report.passed?"✓  Steam IPv6 链路验收通过":"Steam 验收存在未通过项",22,true));foreach(var check in report.checks??new List<Check>()){var p=new StackPanel();var title=Text((check.passed?"✓  ":"✕  ")+check.name,14,true);title.SetResourceReference(TextBlock.ForegroundProperty,check.passed?"Success":"Failure");p.Children.Add(title);var detail=Text(check.detail,12);detail.SetResourceReference(TextBlock.ForegroundProperty,"Muted");p.Children.Add(detail);var row=new Border{CornerRadius=new CornerRadius(12),Padding=new Thickness(14),Margin=new Thickness(0,0,0,9),Child=p};row.SetResourceReference(Border.BackgroundProperty,"Soft");root.Children.Add(row);}if(!String.IsNullOrEmpty(report.report))root.Children.Add(Text("报告："+report.report,11));if(!String.IsNullOrEmpty(report.scope))root.Children.Add(Text(report.scope,11));Log(report.passed?"Steam IPv6 链路通过；实际客户端接管需结合 hosts 与进程连接，报告已保存。":"Steam 验收存在未通过项，请查看真实原因。");}catch(Exception e){progress.Text="Steam 检测未完成："+e.Message;Log("Steam 功能验收未完成。");}finally{busy=false;UpdateRoutingView();UpdateControls();}await Poll();}
 }
}



